### ISSUE TITLE
x509: certificate is valid for *.purplekraken.com, not purplekraken.com

### ISSUE THREAD

**Issue by rikatz** [flimberger/gojail#4]
While doing a go get into the module, it seems the certificate was issued to *.domain but not for the TLD :)

Can workaround here, but just as a heads up

**Comment by flimberger** [comment]
Yeah, I know. I've got it on the radar for quite some time, but I haven't yet gotten around to fix it.
Having an issue here for it helps me pressuring myself in fixing the setup already! :wink:

**Comment by flimberger** [comment]
I finally fixed my setup, sorry for taking so long.
